conn_lc:if conn:if conn_POS:IN with_prev_full:screen_if xxx£
conn_lc:and conn:and conn_POS:CC xxx£
conn_lc:so conn:so conn_POS:RB with_prev_full:and_so xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:up_and xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:reply_and xxx£
conn_lc:also conn:also conn_POS:RB with_prev_full:can_also xxx£
conn_lc:while conn:while conn_POS:IN with_prev_full:conversation_while xxx£
conn_lc:but conn:But conn_POS:CC xxx£
conn_lc:and conn:And conn_POS:CC xxx£
