conn_lc:while conn:while conn_POS:IN with_prev_full:fireplace_while xxx£
conn_lc:and conn:And conn_POS:CC xxx£
conn_lc:so conn:so conn_POS:IN with_prev_full:and_so xxx£
conn_lc:and conn:And conn_POS:CC xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:floor_and xxx£
conn_lc:and conn:And conn_POS:CC with_prev_full:''_and xxx£
conn_lc:then conn:then conn_POS:RB with_prev_full:and_then xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:house_and xxx£
