conn_lc:after conn:after conn_POS:IN with_prev_full:right_after xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:,_and xxx£
conn_lc:so conn:so conn_POS:RB with_prev_full:and_so xxx£
conn_lc:but conn:but conn_POS:CC with_prev_full:,_but xxx£
conn_lc:and conn:And conn_POS:CC xxx£
conn_lc:as_soon_as conn:as_soon_as conn_POS:RB_RB_IN with_prev_full:again_as_soon_as xxx£
conn_lc:so conn:so conn_POS:CC with_prev_full:,_so xxx£
