conn_lc:while conn:while conn_POS:IN with_prev_full:to_while xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:first_and xxx£
conn_lc:then conn:then conn_POS:RB with_prev_full:and_then xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:about_and xxx£
conn_lc:then conn:then conn_POS:RB with_prev_full:and_then xxx£
conn_lc:then conn:then conn_POS:RB with_prev_full:and_then xxx£
conn_lc:because conn:because conn_POS:IN with_prev_full:value_because xxx£
