conn_lc:so conn:so conn_POS:IN with_prev_full:\_so xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:,_and xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:,_and xxx£
conn_lc:because conn:because conn_POS:IN with_prev_full:that_because xxx£
conn_lc:so conn:so conn_POS:IN with_prev_full:,_so xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:''_and xxx£
conn_lc:so conn:so conn_POS:IN with_prev_full:and_so xxx£
conn_lc:so conn:so conn_POS:IN with_prev_full:,_so xxx£
