conn_lc:as conn:as conn_POS:IN with_prev_full:myself_as xxx£
conn_lc:when conn:when conn_POS:WRB with_prev_full:space_when xxx£
conn_lc:so conn:so conn_POS:RB with_prev_full:and_so xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:,_and xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:,_and xxx£
conn_lc:also conn:also conn_POS:RB with_prev_full:was_also xxx£
conn_lc:then conn:then conn_POS:RB with_prev_full:and_then xxx£
